### ISSUE TITLE
Make Mock and Cache middleware naming strategies configurable

### ISSUE THREAD

**Issue by csarrazi** [csarrazi/guzzle-cache-middleware#2]
Currently, naming strategies are defined as a private property of the storage adapters.

Our goal is to expose naming and storage strategies, in order to support new types of requests / APIs (GraphQL, for example, but not only).

See csarrazi/CsaGuzzleBundle#187

**Comment by andreicio** [comment]
I made a PR #7 with the necessary changes and I'll add another one on the main project, since that's where the symfony services are declared.

**Comment by csarrazi** [comment]
Thanks @andreicio! I'll review your PR later this week!

**Comment by Tobion** [comment]
@andreicio are you still planning to make the naming strategy configurable in https://github.com/csarrazi/CsaGuzzleBundle? It could still be used in user-land with a compiler pass. But having it in the bundle directly would be more consistent.

**Comment by andreicio** [comment]
My PR added the naming strategy as a constructor parameter, because originally you would need to replace the storage adapter in order to change the naming, and extending the existing one would not work.
At the moment the changes are only on master, so the first thing needed is a new tag. I see that there's already a request for a new tag supporting sf 5.0, so that might happen soon.
Having a configuration option in the CsaGuzzleBundle would be nice, but you can very easily replace the mock storage service definition even without a compiler pass.

@csarrazi let me know if I can be of assistance in any of this.

**Comment by csarrazi** [comment]
Hey @andreicio, thanks for the help. Don't hesitate to make a PR on the bundle to provide this.

I already tagged the bundle and libraries with a new version since your PR, but this could be a nice addition for version 3.3 of the bundle! :)

**Comment by csarrazi** [comment]
By the way, I'm closing this ticket, as the feature actually exists in the middleware, it just needs to be implemented in the bundle itself!
